"""drop source nodes

Revision ID: 322abbb3e5c5
Revises: 211abd762a89
Create Date: 2026-08-25 11:59:31.392988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '322abbb3e5c5'
down_revision: Union[str, Sequence[str], None] = '211abd762a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_nodes_position'), table_name='source_nodes')
    op.drop_index(op.f('tag'), table_name='source_nodes')
    op.drop_table('source_nodes')
    op.drop_column('answers', 'source_tags')
    op.drop_column('ask_settings', 'fallback_source_tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.

    Restores the shape, never the content: which tags each answer cited is gone
    the moment `upgrade()` runs. Every row comes back citing nothing.

    The `server_default` is load-bearing rather than cosmetic — MySQL refuses to
    add a NOT NULL column to a table that already has rows unless it is told what
    to put in them, and a JSON default has to be an expression.
    """
    empty = sa.text("('[]')")
    op.add_column(
        'ask_settings',
        sa.Column('fallback_source_tags', mysql.JSON(), nullable=False, server_default=empty),
    )
    op.add_column(
        'answers',
        sa.Column('source_tags', mysql.JSON(), nullable=False, server_default=empty),
    )
    op.create_table('source_nodes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tag', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=60), nullable=False),
    sa.Column('target', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('position', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('tag'), 'source_nodes', ['tag'], unique=True)
    op.create_index(op.f('ix_source_nodes_position'), 'source_nodes', ['position'], unique=False)
    # ### end Alembic commands ###
