"""initial content schema

Revision ID: 066e49f7275d
Revises: 
Create Date: 2026-08-24 18:41:24.217510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066e49f7275d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portrait_placeholder', sa.String(length=160), nullable=False),
    sa.Column('portrait_image', sa.String(length=255), nullable=False),
    sa.Column('paragraphs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('source_tags', sa.JSON(), nullable=False),
    sa.Column('is_chip', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_position'), 'answers', ['position'], unique=False)
    op.create_table('ask_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placeholder', sa.String(length=200), nullable=False),
    sa.Column('question_limit', sa.Integer(), nullable=False),
    sa.Column('fallback', sa.Text(), nullable=False),
    sa.Column('fallback_source_tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cta', sa.String(length=160), nullable=False),
    sa.Column('colophon', sa.String(length=255), nullable=False),
    sa.Column('place', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('footnotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_footnotes_position'), 'footnotes', ['position'], unique=False)
    op.create_table('nav_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('href', sa.String(length=120), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_nav_items_position'), 'nav_items', ['position'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=False),
    sa.Column('availability', sa.String(length=200), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('specialities', sa.JSON(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('phone_href', sa.String(length=80), nullable=False),
    sa.Column('linkedin', sa.String(length=255), nullable=False),
    sa.Column('github', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('points', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('link_label', sa.String(length=80), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_position'), 'projects', ['position'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_position'), 'roles', ['position'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('eyebrow', sa.String(length=120), nullable=False),
    sa.Column('heading', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_sections_position'), 'sections', ['position'], unique=False)
    op.create_table('source_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('target', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag')
    )
    op.create_index(op.f('ix_source_nodes_position'), 'source_nodes', ['position'], unique=False)
    op.create_table('stack_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pills', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stack_groups_position'), 'stack_groups', ['position'], unique=False)
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('suffix', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_position'), 'stats', ['position'], unique=False)
    op.create_table('stack_tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('where_used', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['stack_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stack_tiles_group_id'), 'stack_tiles', ['group_id'], unique=False)
    op.create_index(op.f('ix_stack_tiles_position'), 'stack_tiles', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stack_tiles_position'), table_name='stack_tiles')
    op.drop_index(op.f('ix_stack_tiles_group_id'), table_name='stack_tiles')
    op.drop_table('stack_tiles')
    op.drop_index(op.f('ix_stats_position'), table_name='stats')
    op.drop_table('stats')
    op.drop_index(op.f('ix_stack_groups_position'), table_name='stack_groups')
    op.drop_table('stack_groups')
    op.drop_index(op.f('ix_source_nodes_position'), table_name='source_nodes')
    op.drop_table('source_nodes')
    op.drop_index(op.f('ix_sections_position'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_roles_position'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_projects_position'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('profile')
    op.drop_index(op.f('ix_nav_items_position'), table_name='nav_items')
    op.drop_table('nav_items')
    op.drop_index(op.f('ix_footnotes_position'), table_name='footnotes')
    op.drop_table('footnotes')
    op.drop_table('contact_content')
    op.drop_table('ask_settings')
    op.drop_index(op.f('ix_answers_position'), table_name='answers')
    op.drop_table('answers')
    op.drop_table('about_content')
    # ### end Alembic commands ###
